# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Theresa Ma
email: theresa01.ma@gmail.com
description: theresa ma is a software engineer among other things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theresa.ma" # the base hostname & protocol for your site
twitter_username: mapotato
github_username:  theresama

collections:
  essays:
    output: true
    permalink: /:collection/:name
  pictures:
    output: true
    permalink: /:collection/:name
  misc:
    output: true
    permalink: /works/:name

defaults:
  - scope:
      path: ""
      type: pictures
    values:
      layout: page
  - scope:
      path: "assets/images/bw"
    values:
      project: bw
  - scope:
      path: "assets/images/berlin"
    values:
      project: berlin
  - scope:
      path: "assets/images/people"
    values:
      project: people
  - scope:
      path: "assets/images/textures"
    values:
      project: austria
  - scope:
      path: "_posts/tumblr/vacuous-truths"
    values:
      layout: archive
  - scope:
      path: "_posts/tumblr/travel"
    values:
      layout: travel
  - scope:
      path: "assets/images"
    values:
      type: imgs

# Build settings
markdown: kramdown

